language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: pchPtk/FYZoGWcYjbK5QS2KH6HVKcTc9UWgtxS8xEx9ieq1eNh7/rA8eYD9AWc1zBXOfbETTWYLBarViWeWozw3KNJsuac/9pkGMiXK22nvNu8R5rQwyPnymNdjnUdLQ/77AwET18FWDxtjOUF9fwjCR1NSfaPXzg3dX9JETq6E=
  app: bukget-monitor
  on:
    repo: BukGet/monitor
